import About from '@/Components/About'
import Profile from '@/Components/Profile'
import ProjectsCard from '@/Components/ProjectsCard'
import Skill from '@/Components/Skill'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'

export default function Home() {
  const [items, setItems] = useState([])
  // Change this to any username whose repositories you want to get
  const [user] = useState("SametYurtoglu") //github isminiz yazın aksi takdirde hata alırsınız

  useEffect(() => {
    const fetchRepos = async () => {
      const res = await fetch(
        `https://api.github.com/users/${user}/repos?per_page=6&sort=updated`
      )
      const data = await res.json()
      setItems(data)
    }

    fetchRepos()
  }, [user])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full h-screen items-center justify-center">
        <div className="flex flex-col items-center gap-2">
          <div className='relative w-28 h-28'>
            <Image alt='image' src={'/images/logo.png'} fill className='rounded-full border-4 border-gray-700 hover:scale-110 duration-300' />
          </div>
          <div className="text-center text-white">
            <h1>Samet</h1>
            <span>FrontEnd Developer</span>
            <p className='text-gray-400 text-base w-[400px] md:w-[500px]'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque sunt odio iste quo reprehenderit hic consequuntur nihil minima quod rem nemo perspiciatis corrupti suscipit obcaecati eos animi officiis, voluptates accusamus?</p>
          </div>
          <div className="flex gap-5">
            <button>Instagram</button>
            <button>Youtube</button>
            <button>Discord</button>
          </div>
        </div>
      </div>

      {/* Skills */}
      <div>
        <Skill />
      </div>
      {/* Skills end */}

      {/* Projects Card */}
      <div className="flex flex-col gap-y-10 my-16">
        <div className="bg-gray-800/30 w-full h-[4rem] flex items-center">
          <h1 className='container mx-auto text-gray-300 font-medium text-xl'>Projects</h1>
        </div>
        <div className="container mx-auto">
          <ProjectsCard />
        </div>
      </div>
      {/* Projects Card end*/}

      {/* Github Repo */}
      <div className="flex flex-col gap-y-10 ">
        <div className="bg-gray-800/30 w-full h-[4rem] flex items-center">
          <h1 className='container mx-auto text-gray-300 font-medium text-xl flex gap-3 items-center'>
            Github Repository
            <a href="https://github.com/SankThomas/github-users" className='text-blue-600 underline text-sm' target={'_blank'} rel="noreferrer">Producer</a>
          </h1>
        </div>
        <div className="container mx-auto">
          {!items ? (
            ''
          ) : (
            <div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3 pb-20">
              {items.map((item) => (
                <Profile key={item.id} {...item} />
              ))}
            </div>
          )}
        </div>
      </div>
      {/* Github Repo End */}


      {/* About */}
      <div className="">
        <About />
      </div>
      {/* About End */}
    </>
  )
}
